DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  muscle_group TEXT NOT NULL,
  exercise_name TEXT NOT NULL,
  set_count INTEGER NOT NULL,
  reps INTEGER NOT NULL,
  amt_weight INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);